### ISSUE TITLE
Run MPRAsnakeflow on nullomers

### ISSUE THREAD

**Issue by visze** [kircherlab/MPRAsnakeflow#1]
Run MPRAsnakeflow on nullomers to see the stats for the MPRA (especially the DNA).

input data folder: `/fast/groups/ag_kircher/MPRA/MPRAsnakeflow/resources/Nullomers`

output data folder: `/fast/groups/ag_kircher/MPRA/MPRAsnakeflow/results/nullomers`

Config is:
```
nullomers:
  bc_length: 15
  umi_length: 16
  data_folder: resources/Nullomers/data
  experiment_file: resources/Nullomers/experiment.csv
  demultiplex: False
  assignments:
    october_nullomer2bc: resources/Nullomers/october_nullomer2bc.tsv.gz
  design_file: resources/Nullomers/design_file.fa
  configs:
    noZeros:
      bc_threshhold: 10
      minDNACounts: 1
      minRNACounts: 1
```

No label file (maybe we can generate one with DISTAL, MID and PROXIMAL.
