### ISSUE TITLE
Oh so many collisions....

### ISSUE THREAD

**Issue by dagarfield** [kircherlab/MPRAsnakeflow#183]
We have an unusual design in which we have some elements we are testing that differ from one another by only 1-2bp. 
Do you have suggestions for mapping parameters (and mapper) that would work well in this situation with 200bp elements? (I suppose you  must have similar cases when doing variant MPRAs).

**Comment by visze** [comment]
Hey. Yes variants is similar and not unusual at all.

Using the standard should be fine (bbmap with mapq 30). Maybe you have to lower the mapq but you have to see it. We are still investigating the best option here. But for now we do not have a better solution. Hope it works!

**Comment by dagarfield** [comment]
OK, solid. That makes sense, but I fear I've run into some sort of complication in how the config file work for bpmap.
This is my command (**using the .sif file derived in your tutorial**, which I fear may be the root of the issue)

> runContainer("snakemake --configfile MPRA_snakeflow_files/example_assignment_bbmap.yaml -n --quiet rules")

This leads to 

```
WorkflowError in file /data/MPRAsnakeflow/workflow/rules/common.smk, line 16:
Error validating config file.
ValidationError: 200 is not of type 'object'

Failed validating 'type' in schema['properties']['assignments']['patternProperties']['^([^_\\.]+)$']['properties']['alignment_tool']['allOf'][1]['then']['properties']['configs']['properties']['sequence_length']:
    {'type': 'object',
     'properties': {'min': {'type': 'integer'}, 'max': {'type': 'integer'}},
     'additionalProperties': False,
     'required': ['min', 'max']}

On instance['assignments']['exampleAssignment']['alignment_tool']['configs']['sequence_length']:
    200
```

The config file is derived from the bpmap example

```
---
version: "0.4"
assignments:
  exampleAssignment: # name of an example assignment (can be any string)
    bc_length: 15
    alignment_tool:
      split_number: 10 # number of files fastq should be split for parallelization
      tool: bbmap
      configs:
        min_mapping_quality: 30 # 30 is default for bbmap
        sequence_length: 200 # sequence length of design excluding adapters.
        alignment_start: 1 # start of an alignment in the reference/design_file. Here using 15 bp adapters. Can be different when using adapter free approaches
    FW:
      - my_data/out_R1.fastq.gz
    BC:
      - my_data/out_bc.fastq.gz
    REV:
      - my_data/out_R2.fastq.gz
    design_file: my_data/final_selected_elements.fasta
    configs:
      default: {} # name of an example filtering config
```
