### ISSUE TITLE
Clarification Needed on MPRAsnakeflow (v0.4.4) Assignment QC Report Statistics

### ISSUE THREAD

**Issue by biozzq** [kircherlab/MPRAsnakeflow#184]
Dear all,

I am working on linking barcodes and CRS using MPRAsnakeflow v0.4.4 and have encountered questions regarding the Assignment QC report. Below are the details:

Input Data Details:

The input files `barcode.fq.gz, fwd.fq.gz, rev.fq.gz` each contain 9,863,805 reads.

Raw data BCs: 5,778,554

Does this represent the number of unique barcode sequences after deduplication of the `barcode.fq.gz` file?

Filtered data BCs: 943,356

Could you help explain why the filtered BC count (943,356) is less than 10% of the original sequencing reads (9.8M)? This ~90% reduction appears abnormally high. Are there known technical or analytical factors that might explain such a significant loss during processing?"

![Image](https://github.com/user-attachments/assets/d54d0d75-f9b4-4d30-a50d-42244b02add1)

Thank you for your time and assistance.

Best regards,
Zheng zhuqing

**Comment by visze** [comment]
I see you point. Where are all my barcodes? I though I had a quick answer but it turns out I have to look closer at it. I will come back to you soon.

**Comment by visze** [comment]
Ok I found it. What is not shown in the statistics and missing between raw and filtered counts are all barcodes that have not the exact length of the barcode. The length is defined in the config file.

So maybe the config file is wrong or the input barcode contains sequences longer or shorter as the barcode.

Side remark: I will add the number of length Missmatch barcodes to a further version of MPRAsnakeflow

**Comment by biozzq** [comment]
Dear @visze 

According to the following statistics, all the input barcode sequences are 15 bases in length, consistent with the config file setting. This suggests that the loss is not due to length discrepancies, but rather because the sequences corresponding to these barcodes may not have properly matched the CRS. Would this interpretation be correct?
```
seqkit stats barcode.fq.gz
file           format  type   num_seqs      sum_len  min_len  avg_len  max_len
barcode.fq.gz  FASTQ   DNA   9,863,805  147,957,075       15       15       15
```
```
cat config_assignment.yaml 
---
version: "0.4.4"
assignments:
  Assignment:
    bc_length: 15
    alignment_tool:
        split_number: 1
        tool: bbmap
        configs:
          min_mapping_quality: 30
          sequence_length: 150
          alignment_start: 1
    FW:
      - fwd.fq.gz
    BC:
      - barcode.fq.gz
    REV:
      - rev.fq.gz
    design_file: design.change.fa
    configs:
      default: {}
```

Best,
Zheng zhuqing
