### ISSUE TITLE
Help with variant analysis in MPRAsnakeflow using random barcodes and single replicate

### ISSUE THREAD

**Issue by 123zelia** [kircherlab/MPRAsnakeflow#204]
Dear Visze,
Thank you for your great work on MPRAsnakeflow.
I’m currently working on an MPRA experiment with randomly generated barcodes and only one replicate per condition. I would like to perform variant-level quantification (e.g., ref vs alt), but I am not sure how to properly configure the variants section in the config file.

My specific questions:
1.My barcodes are randomly assigned. How should I perform variant quantification with only one replicate?
In config.yaml, the variants section requires a map file. What exactly should this variant_map.tsv look like?

![Image](https://github.com/user-attachments/assets/230774c3-42a0-4d43-9d29-d7302e059f0e)

Can you provide an example format?

Given that I have FASTA entries such as:
>ref_rs13691
TATAAAAGGGAAAATATATTTATAAGAAAGGGATAAAGGTAATAGAGCCCTTCTGCCCCCCACCCACCAAATTTACACAACAAAATGACATGTTCGAATGTGAAAGGTCATAATAGCTTTCCCATCATGAATCAGAAAGATGTGGACAGCTTGATGTTTTA
>alt_rs805257
GCTCCCTACCAATACAAGTCTCTGCATGACCCCCACGCCTTTCCCAAGGGTTTCCAAGTTTATCATTCTCAAGCAAGAACCGGGCTCCTCCTTTTCTCACGGGTTGGGGGCGATTGTCAGGTCCCTTTCACCGGAATCCACACATCCCCCCTCCGCTCCTC

my code like this:
```yaml
---
version: "0.5"
assignments:
  owndata_assign_0507:
    strand_sensitive:
      enable: false
      #forward_adapter: ""
      #reverse_adapter: "GGCCTAACTGGCCGCTTGACG"
    bc_length: 20
    BC_rev_comp: false
    linker: TCTAGAGGTTCGTCGACGCGATCGCAGGAGCCGCAGTG
    alignment_tool:
      split_number: 30
      tool: exact
      configs:
        sequence_length: 161
        alignment_start: 1
    FW:
      - Mpra_als_seqdata/data/Zeng-1st_S99_R1.fastq.gz
    REV:
      - Mpra_als_seqdata/data/Zeng-1st_S99_R2_trimmed.fastq.gz
    design_file: Mpra_als_seqdata/data/design_rev_0507.fa
    design_check:
      fast: true
      sequence_collitions: false
    NGmerge:   
      min_overlap: 18
      min_dovetailed_overlap: 50
      frac_mismatches_allowed: 0.1
    configs:
      default:
        fraction: 0.75  
        min_support: 3        
experiments:
  owndata_count_0507:
    bc_length: 20
    data_folder: Mpra_als_seqdata/data
    experiment_file: /Mpra_als_seqdata/data/experiment_new.csv
    demultiplex: false
    assignments:
      fromWorkflow:
        type: config
        assignment_name: owndata_assign_0507
        assignment_config: default
    design_file: Mpra_als_seqdata/data/design_rev_0507.fa
    configs:
      default:
        filter:
          bc_threshold: 5
          min_rna_counts: 1
          min_dna_counts: 1
          outlier_detection:
            times_zscore: 3
            method: rna_counts_zscore
    variants:
      default: {}
```
