### ISSUE TITLE
BBMap Query Name Length Error in MPRAsnakeflow Pipeline

### ISSUE THREAD

**Issue by Vlasovets** [kircherlab/MPRAsnakeflow#205]
Dear MPRAsnakeflow team,

First of all, thank you for developing this excellent tool. The clear documentation and Python-based implementation are a welcome change in the bioinformatics landscape—well done.

I was able to run the [example notebook](https://github.com/kircherlab/MPRAsnakeflow_tutorial/blob/main/tutorial_assignment.ipynb) without any issues. However, when applying the same workflow to my own dataset, I encountered a blocking error during the BBMap alignment step.

When running the alignment, the pipeline fails with the following error:

```
[E::sam_parse1] query name too long
samtools view: error reading file "-"
samtools view: error closing "-": -5
```

This is followed by multiple Java exceptions related to broken pipes and terminated threads.

I manually inspected the read headers: they are **55 characters long**, which is well below the SAM format limit of **255 characters**.
The error only occurs when using the full dataset. When I test the pipeline on a subset of reads, it completes without issue.

---

## Attempted Fixes

In [`mapping_bbmap.smk`](https://github.com/kircherlab/MPRAsnakeflow/blob/master/workflow/rules/assignment/mapping_bbmap.smk), I attempted to mitigate the issue by adding the following BBMap parameters:

```bash
sam=1.4 usejni=t shortname=t
```

Unfortunately, the issue persisted. It's unclear whether these parameters are sufficient or whether other changes are needed (e.g., modifying the way output is piped to samtools).

---

## Configuration

Below is the relevant snippet from my `config.yaml` file:

```yaml
version: "0.5"
assignments:
  assignMPRAworkshop:
    bc_length: 12
    BC_rev_comp: false
    linker: GAATTCATCTGGTACCTCGGTTCACGCAATG
    alignment_tool:
      split_number: 30
      tool: bbmap
      configs:
        sequence_length: 300
        alignment_start: 1
        min_mapping_quality: 30
    FW:
      - real_data/assignment/forward/24L005276_S11_L001_R1_001.fastq.gz
    REV:
      - real_data/assignment/reverse/24L005276_S11_L001_R2_001.fastq.gz
    design_file: real_data/assignment/designed_oligos_deduplicated.fasta
    configs:
      default:
        min_support: 1
        fraction: 0.51
```

---

## Question

Are there additional BBMap parameters (or samtools workarounds) that could help resolve the “query name too long” error?

---

## Additional File

Log file:  
📄 [mapping.bbmap.assignMPRAworkshop.6.log](https://github.com/user-attachments/files/20761415/mapping.bbmap.assignMPRAworkshop.6.log)

---

Thank you in advance for your time!

Best regards,  
Oleg

**Comment by visze** [comment]
Hi Oleg,

Thanks a lot for your nice words!

I have never seen this error before and I also have no clue what's going on. But I have some questions that might help to locate the issue:

- Does this happen only at split 6 (input `results/assignment/assignMPRAworkshop/fastq/merge_split6.join.fastq.gz`)? You should have 30 splits of your input file. Do the others run normally or do they have the same error? You can prevent Snakemake from stopping immediately by using the additional command `--keep-going`. 
- Did you have a look at the input fastqs of split 6? Do they look normal?

My first intuition was that something here might be misconfigured:

```yaml
bc_length: 12
BC_rev_comp: false
linker: GAATTCATCTGGTACCTCGGTTCACGCAATG
```

But since you were able to run it on a smaller dataset, it should be fine.

Side remark:

I would not recommend using `min_support=1` and `fraction=0.51`.
