### ISSUE TITLE
Simplified config schemas

### ISSUE THREAD

**Issue by lotard** [kircherlab/MPRAsnakeflow#77]
This config schema by @visze (unimplemented) looks better to me than previous one, because it's more human readable:
```
    assignments:
      october_nullomer2bc: resources/Nullomers/october_nullomer2bc.tsv.gz
      october_nullomer2bc_fixed: resources/Nullomers/october_nullomer2bc_correctLength_removedMultiAssignments.tsv.gz
    configs:
      noZeros:
        bc_threshold: 10
        minDNACounts: 1
        minRNACounts: 1
```
This may require detection of `config` vs `file` assignment automatically (by extension?)

Here's a (mock-up) of the current, more complicated schema:
```
    assignments:
      october_nullomer2bc:
        type: file
        assignment_file: resources/Nullomers/october_nullomer2bc.tsv.gz
      october_nullomer2bc_fixed:
        type: file
        assignment_file: resources/Nullomers/october_nullomer2bc_correctLength_removedMultiAssignments.tsv.gz
    configs:
      noZeros:
        bc_threshold: 10
        DNA:
          min_counts: 1
        RNA:
          min_counts: 1
```
